export const ANIMALS = [
  'alligator', 'ant', 'bear', 'bee', 'bird', 'camel', 'cat', 'cheetah',
  'chicken', 'chimpanzee', 'cow', 'crocodile', 'deer', 'dog', 'dolphin',
  'duck', 'eagle', 'elephant', 'fish', 'fly', 'fox', 'frog', 'giraffe', 'goat',
  'goldfish', 'hamster', 'hippopotamus', 'horse', 'kangaroo', 'kitten', 'lion',
  'lobster', 'monkey', 'octopus', 'owl', 'panda', 'pig', 'puppy', 'rabbit',
  'rat', 'scorpion', 'seal', 'shark', 'sheep', 'snail', 'snake', 'spider',
  'squirrel', 'tiger', 'turtle', 'wolf', 'zebra'
]

export const ADJECTIVES = [
  'adorable', 'afraid', 'alert', 'amusing', 'angry', 'awful', 'bashful',
  'beautiful', 'bored', 'brave', 'busy', 'calm', 'carefree', 'careless',
  'caring', 'challenging', 'cheerful', 'chilly', 'clever', 'clumsy', 'cowardly',
  'cozy', 'crabby', 'cranky', 'crawling', 'crazy', 'creaky', 'creeping',
  'creepy', 'crispy', 'cruel', 'curly', 'deep', 'difficult', 'dreadful', 'dull',
  'easy', 'endless', 'excited', 'fair', 'fantastic', 'fluttering', 'foolish',
  'foul', 'freezing', 'friendly', 'fussy', 'fuzzy', 'generous', 'gentle',
  'glassy', 'gloomy', 'glowing', 'good', 'grand', 'great', 'greedy', 'grimy',
  'happy', 'hard', 'hardworking', 'hasty', 'heavy', 'hideous', 'hopeful',
  'horrid', 'huge', 'icy', 'joyful', 'kind', 'lazy', 'long', 'loud', 'loyal',
  'lumpy', 'meek', 'messy', 'mighty', 'moody', 'muffled', 'muggy', 'nasty',
  'nimble', 'odd', 'petite', 'plump', 'plush', 'polite', 'proud', 'puny',
  'quick', 'quiet', 'rapid', 'rich', 'rude', 'rusty', 'scared', 'selfish',
  'shining', 'shrill', 'silly', 'simple', 'sizzling', 'sleepy', 'slimy',
  'sloppy', 'small', 'smelly', 'smooth', 'snug', 'soaring', 'sparkling',
  'speedy', 'spiky', 'splendid', 'spoiled', 'starving', 'steaming', 'stiff',
  'still', 'stingy', 'stinky', 'strict', 'stuffed', 'sturdy', 'surprised',
  'swift', 'tense', 'thrifty', 'tiny', 'tough', 'tricky', 'truthful', 'ugly',
  'vast', 'wild', 'wise', 'wonderful', 'worried', 'wrinkly'
];

export const WORDPAIRS = [
  'Biscuits and Gravy',
  'Salt and Pepper',
  'Mac and Cheese',
  'Pineapple Pizza',
  'Two Peas in a Pod',
  'Apples and Oranges',
  'Dead or Alive',
  'Bread and Butter',
  'Birds and Bees',
  'Short and Fat',
  'Command and Conquer ',
  'Adam and Eve',
  'Adam and Steve',
  'Bacon and Eggs',
  'Body and Soul',
  'Bricks and Mortar',
  'Lock and Key',
  'Chicken and Rice',
  'Peaches and Cream',
  'Pen and Pencil',
  'Pork and Beans',
  'Pots and Pans',
];